version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    labels: ["A2-insubstantial", "B0-silent", "C1-low", "E2-dependencies"]
    schedule:
      interval: "daily"
  - package-ecosystem: github-actions
    directory: '/'
    labels: ["A2-insubstantial", "B0-silent", "C1-low", "E2-dependencies"]
    schedule:
      interval: daily

  # Python dependencies for Linode
  - package-ecosystem: "pip"
    directories:
      - "/.github"
    groups:
      linode-dependencies:
        dependency-type: "production"
        applies-to: version-updates
    schedule:
      interval: "monthly"
